# Download and install EPEL for Centos/RHEL version 6
- name: Download EPEL Repo - Centos/RHEL 6
  get_url: url=http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm dest=/tmp/epel-release-latest-6.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: Install EPEL Repo - Centos/RHEL 6
  command: rpm -ivh /tmp/epel-release-latest-6.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

# Download and install EPEL for Centos/RHEL version 7
- name: Download EPEL Repo - Centos/RHEL 7
  get_url: url=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/tmp/epel-release-latest-7.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install EPEL Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/epel-release-latest-7.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

# Download and install EPEL for Ubuntu
- name: Add EPEL Repo - Ubuntu
  apt:
    deb: https://dl.fedoraproject.org/pub/epel/epel-release-latest-ubuntu.deb
  when: "ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'"

- name: Install EPEL Repo - Ubuntu
  command: dpkg -i /tmp/epel-release-latest-ubuntu.deb
  when: "ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'"

# Install libselinux-python for Ubuntu if needed
#- name: Install libselinux-python for Ubuntu
#  apt:
#    name: libselinux-python
#  when: "ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'"
