---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy the code from repository
  git:
    repo: "{{ repository }}"
    dest: /vars/www/html/

- name: Creates the index.php file
  template:
    src: index.php.j2
    dest: /vars/www/html/index.php
